FROM mcr.microsoft.com/dotnet/sdk:10.0 AS builder

WORKDIR /app

COPY . .

RUN dotnet restore

RUN dotnet tool install --global dotnet-ef

ENV PATH="${PATH}:/root/.dotnet/tools"

RUN dotnet publish --no-restore -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS runner

WORKDIR /app

COPY --from=builder /app/publish .

EXPOSE 5000

CMD [ "dotnet", "TaskHub.Api.dll", "--urls", "http://0.0.0.0:5000" ]